sequenceDiagram
	participant browser
	participant server

	browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
	activate server
	server-->>browser: another HTML document written in index.js ( server code )
	deactivate server
	
	browser->>server GET https://studies.cs.helsinki.fi/exampleapp/main.css
	activate server
	server->>browser: css file
	desactivate server
	
	browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
	activate server
	server-->>browser: another Javascript file
	deactivate server

	Note: The browser fetch data.json from the server for the Javascript code

	browser->>server GET https://studies.cs.helsinki.fi/exampleapp/data.json 
	activate server
	server->>browser: JSON
	desactivate server
	
	Note: The browser execute the callback function that renders the notes
